package com.crimson.core.subtitles

import com.crimson.core.audio.SpeechMeter
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Automatic sync against real speech: the mock server's caption test film, whose soundtrack is
 * synthesised dialogue with explosions and a music bed between the lines. Generated by
 * `tools/mock-xtream/make_dialogue.py` and not committed, so this is skipped where it is absent.
 *
 * The meter hears the soundtrack exactly as the app's audio tap does, and the subtitle file the
 * mock hands out runs 2.7 s early; sync has to find that from the first minute and a half.
 */
class SyncOnRealAudioTest {

    private val media = File("../tools/mock-xtream/media")

    @Test
    fun `finds the offset of an early subtitle file from the film's own audio`() {
        val wav = File(media, "tts/dialogue.wav")
        val early = File(media, "dialogue_early.srt")
        assumeTrue("caption test media not generated", wav.isFile && early.isFile)

        val bytes = wav.readBytes()
        // A plain 44-byte PCM header, as make_dialogue.py writes it: 48 kHz, stereo, 16-bit.
        val samples = ByteBuffer.wrap(bytes, 44, bytes.size - 44).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer()
        val pcm = ShortArray(samples.remaining()).also { samples.get(it) }
        val rate = 48_000
        val speech = SpeechTimeline(240_000)
        // Only what the app would have heard by its first attempt: the first 95 seconds.
        val heardFrames = rate * 95
        SpeechMeter(rate, 2).feed(pcm, minOf(heardFrames, pcm.size / 2)) { endFrame, level ->
            speech.record(endFrame * 1000L / rate - SpeechMeter.WINDOW_MS / 2, level)
        }

        val track = SubtitleParser.parse(early.readBytes())
        println("real-audio best fit: " + SubtitleSync.bestFit(track, speech))
        val fix = SubtitleSync.estimate(track, speech)
        assertNotNull("no confident sync", fix)
        assertEquals(2_700.0, fix!!.offsetMs.toDouble(), 200.0)
        assertEquals(1.0, fix.scale, 1e-9)
        println("real-audio sync: $fix")
    }
}
